const ProductData = [
    {
      img: require('../ImgData/A1.jpeg'),
      name: 'Demo1',
      price: 2000,
      details: 'Demo1 Details , Demo1 Details , Demo1 Details , Demo1 Details , Demo1 Details',
      type: 'Hoody',
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A2.jpeg'),
      name: 'Demo2',
      price: 1500,
      details: 'Demo2 Details , Demo2 Details , Demo2 Details , Demo2 Details , Demo2 Details',
      type: 'Hoody',
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A3.jpeg'),
      name: 'Demo3',
      price: 3000,
      details: 'Demo3 Details , Demo3 Details , Demo3 Details , Demo3 Details , Demo3 Details',
      type: 'Hoody',
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A4.jpeg'),
      name: 'Demo4',
      price: 2399,
      details: 'Demo4 Details , Demo4 Details , Demo4 Details , Demo4 Details , Demo4 Details',
      type: 'Hoody',
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A5.jpeg'),
      name: 'Demo5',
      price: 3000,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A6.jpeg'),
      name: 'Demo6',
      price: 2799,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A7.jpeg'),
      name: 'Demo7',
      price: 3500,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A8.jpeg'),
      name: 'Demo8',
      price: 1000,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A9.jpeg'),
      name: 'Demo9',
      price: 3200,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A10.jpeg'),
      name: 'Demo10',
      price: 6599,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A11.jpeg'),
      name: 'Demo11',
      price: 8000,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A12.jpeg'),
      name: 'Demo12',
      price: 2000,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A13.jpeg'),
      name: 'Demo13',
      price: 1799,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A14.jpeg'),
      name: 'Demo14',
      price: 1899,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A15.jpeg'),
      name: 'Demo15',
      price: 9999,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A16.jpeg'),
      name: 'Demo16',
      price: 15000,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A17.jpeg'),
      name: 'Demo17',
      price: 20000,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A18.jpg'),
      name: 'Demo18',
      price: 2499,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A19.jpeg'),
      name: 'Demo19',
      price: 3300,
      isChaked: false,
      count:1,
    },
    {
      img: require('../ImgData/A20.jpeg'),
      name: 'Demo20',
      price: 3599,
      isChaked: false,
      count:1,
    },
  ]
  

  export default ProductData